In [132]:
import seaborn as sns
import pandas as pd
import numpy as np

In [133]:
train_df = pd.read_excel('/workspaces/SML/SML /Exp 8/train.xlsx')
train_df
test_df = pd.read_excel('/workspaces/SML/SML /Exp 8/test.xlsx')
test_df

,Loan_ID,Gender,Married,Dependents,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Property_Area,Loan_Status
0,7,1,1,0,0,2333,1516.0,95,360,2,1
1,8,1,1,3,0,3036,2504.0,158,360,0,0
2,13,1,1,2,0,3073,8106.0,200,360,2,1
3,20,1,1,0,1,2600,3500.0,115,0,2,1
4,22,1,1,1,0,5955,5625.0,315,360,2,1
...,...,...,...,...,...,...,...,...,...,...,...
172,599,1,1,0,1,9963,0.0,180,360,1,1
173,604,1,0,0,0,3676,4301.0,172,360,1,1
174,605,0,1,1,0,12000,0.0,496,360,0,1
175,608,1,1,2,0,3987,1411.0,157,360,1,1
176,614,0,0,0,1,4583,0.0,133,360,0,0

drop loanid column

In [134]:
train_df = train_df.drop('Loan_ID',axis=1)
train_df

,Gender,Married,Dependents,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Property_Area,Loan_Status
0,1,0,0,0,5849,0,0,360,2,1
1,1,1,1,0,4583,1508,128,360,1,0
2,1,1,0,1,3000,0,66,360,2,1
3,1,1,0,0,2583,2358,120,360,2,1
4,1,0,0,0,6000,0,141,360,2,1
...,...,...,...,...,...,...,...,...,...,...
432,1,1,0,0,3232,1950,108,360,1,1
433,0,0,0,0,2900,0,71,360,1,1
434,1,1,3,0,4106,0,40,180,1,1
435,1,1,1,0,8072,240,253,360,2,1
436,1,1,2,0,7583,0,187,360,2,1

In [135]:
test_df

,Loan_ID,Gender,Married,Dependents,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Property_Area,Loan_Status
0,7,1,1,0,0,2333,1516.0,95,360,2,1
1,8,1,1,3,0,3036,2504.0,158,360,0,0
2,13,1,1,2,0,3073,8106.0,200,360,2,1
3,20,1,1,0,1,2600,3500.0,115,0,2,1
4,22,1,1,1,0,5955,5625.0,315,360,2,1
...,...,...,...,...,...,...,...,...,...,...,...
172,599,1,1,0,1,9963,0.0,180,360,1,1
173,604,1,0,0,0,3676,4301.0,172,360,1,1
174,605,0,1,1,0,12000,0.0,496,360,0,1
175,608,1,1,2,0,3987,1411.0,157,360,1,1
176,614,0,0,0,1,4583,0.0,133,360,0,0

In [136]:
test_df = test_df.drop('Loan_ID',axis=1)
test_df

,Gender,Married,Dependents,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Property_Area,Loan_Status
0,1,1,0,0,2333,1516.0,95,360,2,1
1,1,1,3,0,3036,2504.0,158,360,0,0
2,1,1,2,0,3073,8106.0,200,360,2,1
3,1,1,0,1,2600,3500.0,115,0,2,1
4,1,1,1,0,5955,5625.0,315,360,2,1
...,...,...,...,...,...,...,...,...,...,...
172,1,1,0,1,9963,0.0,180,360,1,1
173,1,0,0,0,3676,4301.0,172,360,1,1
174,0,1,1,0,12000,0.0,496,360,0,1
175,1,1,2,0,3987,1411.0,157,360,1,1
176,0,0,0,1,4583,0.0,133,360,0,0

In [137]:
train_df.isnull().sum()

Gender               0
Married              0
Dependents           0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Property_Area        0
Loan_Status          0
dtype: int64

In [138]:
train_df = train_df.fillna(0)

CASE 1. WITHOUT FEATURE ENGINEERING

In [139]:
X = train_df.drop(columns=['Loan_Status'])
y = train_df['Loan_Status']

In [140]:
print(X)

     Gender  Married  Dependents  Self_Employed  ApplicantIncome  \
0         1        0           0              0             5849
1         1        1           1              0             4583
2         1        1           0              1             3000
3         1        1           0              0             2583
4         1        0           0              0             6000
..      ...      ...         ...            ...              ...
432       1        1           0              0             3232
433       0        0           0              0             2900
434       1        1           3              0             4106
435       1        1           1              0             8072
436       1        1           2              0             7583

     CoapplicantIncome  LoanAmount  Loan_Amount_Term  Property_Area
0                    0           0               360              2
1                 1508         128               360              1
2                    0          66               360              2
3                 2358         120               360              2
4                    0         141               360              2
..                 ...         ...               ...            ...
432               1950         108               360              1
433                  0          71               360              1
434                  0          40               180              1
435                240         253               360              2
436                  0         187               360              2

[437 rows x 9 columns]

In [141]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X,y,test_size=0.2,stratify=y,random_state=42)

In [142]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(x_train)
X_test = sc.transform(x_test)

In [143]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf',gamma=0.67,random_state=42)
classifier.fit(X_train,y_train)

SVC(gamma=0.67, random_state=42)

In [144]:
y_pred = classifier.predict(X_test)

In [145]:
#Make the confusion matrix
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[ 1 27]
 [ 0 60]]

0.6931818181818182

In [148]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
pipeline = Pipeline([
    ('imputer',SimpleImputer(strategy='median')),
    ('scale',StandardScaler())
    ('svm',SVC(class_weight='balanced',probability=True))
])

<>:5: SyntaxWarning: 'tuple' object is not callable; perhaps you missed a comma?
<>:5: SyntaxWarning: 'tuple' object is not callable; perhaps you missed a comma?
/tmp/ipykernel_4596/3454722965.py:5: SyntaxWarning: 'tuple' object is not callable; perhaps you missed a comma?
  ('scale',StandardScaler())

TypeError: 'tuple' object is not callable

In [ ]:
from sklearn.model_selection import GridSearchCV
param_grid = {
    'svm_C': [0.1,1,10,50],
    'svm_gamma':['scale',0.01,0.1],
    'svm_kernel':['rbf','linear']
}
grid = GridSearchCV(pipeline,param_grid,cv=5,scoring='accuracy')
grid.fit(X_train,y_train)
print("Best Parametrs:",grid.best_params_)
print("Best Score",grid.best_score_)